name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd challenge-8282
            echo "Pull latest code"
            git pull

            echo "Stop containers"
            docker compose down

            echo "Build & Run containers"
            docker compose up -d --build